### ISSUE TITLE
Pattern doesn't exist

### ISSUE THREAD

**Issue by KDean-Dolphin** [gs1/gs1-syntax-dictionary#10]
The pattern "NN+NN" doesn't exist anywhere in the AI data.

https://github.com/gs1/gs1-syntax-dictionary/blob/ee18e07a6e66e87a7f2c1e43dd5ab6aeff5b10d8/gs1-syntax-dictionary.txt#L59-L60

**Comment by terryburton** [comment]
It's an amalgam of the `+` syntax used in AI (8030) and the `35nn` syntax used elsewhere. Solely for the purpose of having a single, descriptive example.

**Comment by KDean-Dolphin** [comment]
Ah, my mistake. I searched specifically for "req=01+21", not for "01+21", which was buried in 8030.
