### ISSUE TITLE
Discrepancy in AI 02

### ISSUE THREAD

**Issue by KDean-Dolphin** [gs1/gs1-syntax-dictionary#13]
Per Figure 4.13.2-1 of the GenSpecs, this should be `req=00 req=37`.

https://github.com/gs1/gs1-syntax-dictionary/blob/ca3344bd3bfb00de8672a8adc450186da07fe2e9/gs1-syntax-dictionary.txt#L123

**Comment by terryburton** [comment]
(02) requires (37) which in turn requires (00), therefore the restriction is met.

Such behaviour is used elsewhere to minimise the ruleset.
