### ISSUE TITLE
Replace mmoptss

### ISSUE THREAD

**Issue by KDean-Dolphin** [gs1/gs1-syntax-dictionary#14]
Similarly to #9, the mmoptss option causes problems for structural validators; the value "123" would be perfectly legitimate. I suggest instead replacing "[N..4]mmoptss" with "[N2]mm [N2]ss" to better reflect the requirement.

https://github.com/gs1/gs1-syntax-dictionary/blob/ca3344bd3bfb00de8672a8adc450186da07fe2e9/gs1-syntax-dictionary.txt#L318

**Comment by terryburton** [comment]
Already in progress. Refer to details sent under separate cover. Thanks.

**Comment by terryburton** [comment]
Done with https://github.com/gs1/gs1-syntax-dictionary/commit/0489efc3e6313d00eb9013e2cad025c72acd08ef

**Comment by KDean-Dolphin** [comment]
@terryburton It may be better to replace "mm" with "mi" when referring to minutes. It's unlikely, but should there ever be an AI that is the month number only we would have a conflict. This would also mean replacing "hhmm" with "hhmi".

**Comment by terryburton** [comment]
@KDean-GS1 I'll look around to see if there's a reasonable standard that we might follow.
