### ISSUE TITLE
(dlpkey) explanations?

### ISSUE THREAD

**Issue by nerixs** [gs1/gs1-syntax-dictionary#6]
Hello,
Concerning dlpkey, the AIs concerned are still 22, 10 21 or 235?
I don't quite understand how the GS1 Digital Link primary key works.
Does it condition the validity of a GS1 Digital Link URI? 
Could you explain this further?
Best regards

**Comment by terryburton** [comment]
`dlpkey` relates to section 4.9 Path element order of the GS1 Digital Link Standard: URI Syntax specification.

The tag itself denotes that an AI is a valid GS1 DL URI primary key. The values (where they exist) denote the permissible key qualifier sequences for that primary key.

**Comment by PetaDing-GS1** [comment]
Hello! In addition to Terry's helpful response, GS1 Digital Link primary keys are defined by the [GS1 Digital Link standard: URI Syntax](https://ref.gs1.org/standards/digital-link/uri-syntax/) section 4.3, and are intended to express the GS1 Identification Keys defined by the [GS1 General Specifications](https://ref.gs1.org/standards/genspecs/), in a web URI. Hope that helps! Please reach out again if you need more information.
